version: "3.8"

services:
  api:
    build: .
    command: python -m src
    container_name: password_validation_api
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./:/opt/program
    networks:
      - main_network

networks:
  main_network:
    driver: bridge